name: workflow

on:
 push:
  branches:
    - main
  paths-ignore:
    - 'Readme.md'


jobs:
  integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3
      
      - name: Lint Code
        uses: echo "Linting repository"
      
      - name: Run unit tests
        uses: echo "Running unit tests"
